# Generated by Django 4.1.7 on 2023-03-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(blank=True)),
                ('pages_quantity', models.IntegerField()),
                ('price', models.FloatField(null=True)),
                ('cover_type', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('exist', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
