# Generated by Django 4.1.7 on 2023-03-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(max_length=120),
        ),
    ]
