# Generated by Django 4.1.7 on 2023-03-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='https://wallbox.ru/resize/1600x900/wallpapers/main/201505/a79e36822cb5b91.jpg', upload_to='image/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_type',
            field=models.CharField(max_length=30, verbose_name='Тип обложки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='exist',
            field=models.BooleanField(default=True, null=True, verbose_name='В каталоге?'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_quantity',
            field=models.IntegerField(verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=500, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(max_length=120, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='book', max_length=120, null=True, verbose_name='Наименование'),
        ),
    ]
