# Generated by Django 4.1.7 on 2023-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_book_photo_alter_book_cover_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
